#!/usr/bin/env bash

# shellcheck disable=SC2034 
# shellcheck disable=SC2154

BANCO=usuario.txt

source bantex.sh || {
    echo "Ops, ocorreu algum erro no gerenciador do banco"
exit 1
}


lista(){
    pega_campo 1 > show
    dialog --title "Usuarios" --textbox show 13 30
    rm  show
    init 
}

adiciona(){
        login=$(dialog --stdout --inputbox "Digite o login: " 0 0)
        [ "$login" ] ||  exit 1

        tem_chave "$login" && {
        msg="O usuario ja foi cadastrodo."
        dialog --msgbox "$msg" 6 40
        init 
    }

    nome=$(dialog --stdout --inputbox "Nome completo:" 0 0)
    idade=$(dialog --stdout --inputbox "Digite a idade:" 0 0)
    sexo=$(dialog --stdout --radiolist "sexo:" 0 0 3\
        Feminino "" on Masculino "" off)

    sexo=$(echo $sexo | cut -c1)
    nome=$(echo $nome| mascara)
    msg=$(insere_registro "$login:$nome:$idade:$sexo")
    dialog --title "Resultado" --msgbox "$msg" 6 40
    init
}

remove(){
    usuarios=$(pega_campo 1,2 | sed 1d) 
    usuarios=$(echo "$usuarios" | sed 's/:/ "/;s/$/"/') 

    login=$(eval dialog --stdout               \
        --menu \"Escolha o usuario a remover\" \
        0 0 0 $usuarios)

    msg=$(apaga_registro "$login")
    dialog --title "Resultado" --msgbox "$msg" 6 40
    init
}

sair(){
    dialog --title 'sair'              \
        --yesno                        \
        "\n Sair do sistema agora\n\n" \
    0 0
    [ $? -ne 0 ] || exit 0
    init
}

init(){
    acao=$(dialog --stdout                             \
        --menu "Aplicativo Zuserd - Inteface amigavel" \
        0 0 0                                          \
        lista    "Lista todos os usuarios do sistema"  \
        adiciona "Adiciona um  usuarios do sistema"    \
        remove   "Remove um  usuarios do sistema"      \
        sair "Para sair do sistema ")

    while :
    do
        case "$acao" in 
            lista) lista ;;
            adiciona) adiciona ;;
            remove) remove ;;
            sair) sair ;;
        esac
    done
}
init
